# Generated by Django 3.2.4 on 2021-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='destination',
            field=models.CharField(max_length=200, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Origen'),
        ),
    ]
